blitz/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

from base.api import UserResource, FeedItemResource
from tastypie.api import Api
from django.views.generic import TemplateView

handler500 = 'base.views.server_error'
handler404 = 'base.views.not_found_error'
handler403 = 'base.views.permission_denied_error'
handler400 = 'base.views.bad_request_error'

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(FeedItemResource())

urlpatterns = patterns('',
    (r'^spotter/', include('spotter.urls')),
)
urlpatterns += patterns(
    '',

    url("^/custom-trainer-page$", TemplateView.as_view(template_name="custom_trainer_page.html"), name="custom_trainer_page"),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hijack/', include('hijack.urls')),

    url("^trainer/marc$", TemplateView.as_view(template_name="custom_trainer_page_marc.html")),
    url("^trainer/lexi$", TemplateView.as_view(template_name="custom_trainer_page_lexi.html")),

    url("^all$", 'base.views.market', name='market'),
    url(r'^allclients$', 'base.views.all_clients', name='all_clients'),

    url(r'^post/gym/(?P<pk>\d+)$', 'base.views.single_post_gym', name='single_post_gym'),
    url(r'^post/comment/(?P<pk>\d+)$', 'base.views.single_post_comment', name='single_post_comment'),

    url(r'^login$', 'base.views.login_view', name='login_view'),
    url(r'^logout$', 'base.views.logout_view', name='logout_view'),
    url(r'^forgot-password$', 'base.views.forgot_password', name='forgot_password'),
    url(r'^forgot-password-sent$', 'base.views.forgot_password_sent', name='forgot_password_sent'),
    url(r'^reset-password$', 'base.views.reset_password', name='reset_password'),
    url(r'^reset-password-complete', 'base.views.reset_password_complete', name='reset_password_complete'),

    # url(r'^$', 'base.views.home', name='home'),
    url(r'^$', 'base.views.home', name='home'),
    url(r'^about$', 'base.views.about', name='about'),

    url(r'^profile$', 'base.views.my_profile', name='my_profile'),
    url(r'^profile/c/(?P<pk>\d+)$', 'base.views.client_profile', name='client_profile'),
    url(r'^profile/c/(?P<pk>\d+)/progress$', 'base.views.client_profile_progress', name='client_profile_progress'),
    url(r'^profile/c/(?P<pk>\d+)/history$', 'base.views.client_profile_history', name='client_profile_history'),
    url(r'^profile/c/(?P<pk>\d+)/checkins$', 'base.views.client_profile_checkins', name='client_profile_checkins'),
    url(r'^profile-basic$', 'base.views.set_up_profile_basic', name='profile_basic'),

    url(r'^profile/c/(?P<pk>\d+)/set-macros', 'base.views.set_client_macros', name='set_client_macros'),

    url(r'^client-signup$', 'base.views.client_signup', name='client_signup'),
    url(r'^client-setup$', 'base.views.client_setup', name='client_setup'),
    url(r'^client-setup/(?P<pk>\d+)$', 'base.views.client_blitz_setup', name='client_blitz_setup'),

    url(r'^client-checkin$', 'base.views.client_checkin', name='client_checkin'),

    url(r'^client-survey$', 'base.views.client_survey', name='client_survey'),
    url(r'^trainer-survey$', 'base.views.trainer_survey', name='trainer_survey'),

    url(r'^set-up-profile$', 'base.views.set_up_profile', name='set_up_profile'),

    url(r'^register-trainer$', 'base.views.trainer_signup', name='register_trainer'),
    url(r'^register-trainer-uploads/(?P<pk>\d+)$', 'base.views.trainer_signup_uploads', name='register_trainer_uploads'),

    url(r'^salespage$', 'base.views.my_salespages', name='my_salespages'),

    url(r'^program$', 'base.views.my_programs', name='my_blitz_program'),
    url(r'^view_program/(?P<pk>\d+)$', 'base.views.view_program', name='view_program'),
    url(r'^switch_program$', 'base.views.switch_program', name='switch_program'),

    url(r'^program/members$', 'base.views.my_blitz_members', name='my_blitz_members'),

    url(r'^dashboard$', 'base.views.trainer_dashboard', name='trainer_dashboard'),

    url(r'^log-workout/(?P<week_number>\d+)/(?P<day_char>\w+)$', 'base.views.log_workout', name='log_workout'),
    url(r'^preview-workout/(?P<workoutplan_pk>\d+)/(?P<week_number>\d+)/(?P<day_char>\w+)$', 'base.views.preview_workout', name='preview_workout'),

    url(r'^api/send-message-to-user/(?P<pk>\d+)', 'ff_messaging.views.send_message_to_user', name='send_message_to_user'),
    url(r'^api/new-comment', 'base.views.new_comment', name='new_comment'),
    url(r'^api/blitz_feed$', 'base.views.blitz_feed', name='blitz_feed'),

    url(r'^api/blitz_feed/viewed/mark$', 'base.views.blitz_feed_viewed', name='blitz_feed_viewed'),
    url(r'^api/blitz_feed/count$', 'base.views.get_unviewed_count', name='get_unviewed_count'),

    url(r'^api/blitz/(?P<pk>\d+)$', 'base.views.blitz', name='blitz'),
    url(r'^api/inbox_feed', 'ff_messaging.views.inbox_feed', name='inbox_feed'),
    url(r'^api/comment_like', 'base.views.comment_like', name='comment_like'),
    url(r'^api/comment_unlike', 'base.views.comment_unlike', name='comment_unlike'),
    url(r'^api/gym_session_like', 'base.views.gym_session_like', name='gym_session_like'),
    url(r'^api/gym_session_unlike', 'base.views.gym_session_unlike', name='gym_session_unlike'),
    url(r'^api/checkin_like', 'base.views.checkin_like', name='checkin_like'),
    url(r'^api/checkin_unlike', 'base.views.checkin_unlike', name='checkin_unlike'),
    url(r'^api/new-child-comment', 'base.views.new_child_comment', name='new_child_comment'),

    url(r'^api/save-sets', 'base.views.save_sets', name='save_sets'),

    url(r'^macros/get-macros-for-blitz-week', 'base.views.get_macros_for_blitz_week', name='get_macros_for_blitz_week'),
    url(r'^macros/undo-day', 'base.views.undo_macro_day', name='undo_macro_day'),
    url(r'^macros/save-day', 'base.views.save_macro_day', name='save_macro_day'),
    url(r'api/client_summary/(?P<pk>\w+)', 'base.views.client_summary', name='client_summary'),
    url(r'api/invitee_summary/(?P<pk>\w+)', 'base.views.invitee_summary', name='invitee_summary'),

    url(r'^trainer/dismiss-alert$', 'base.views.trainer_dismiss_alert', name='trainer_dismiss_alert'),
    url(r'^trainer/change-date$', 'base.views.trainer_change_date', name='trainer_change_date'),
    url(r'^trainer/spotter-edit$', 'base.views.spotter_edit', name='spotter_edit'),
    url(r'^trainer/profile/(?P<pk>\d+)$', 'base.views.trainer_profile', name='trainer_profile'),
    url(r'^trainer/blitz-macros-save$', 'base.views.blitz_macros_save', name='blitz_macros_save'),
    url(r'^trainer/client-macros-save$', 'base.views.client_macros_save', name='client_macros_save'),
    url(r'^trainer/invitee-macros-save$', 'base.views.invitee_macros_save', name='invitee_macros_save'),
    url(r'^trainer/client-setup$', 'base.views.client_setup', name='client_setup'),

    # todo: intro views namespaced as intro/[slug]
    url(r'^intro-data-1$', 'base.views.set_intro_1', name='set_intro_1'),

    (r'^api/', include(v1_api.urls)),

    url(r'^sales-blitz$', 'base.views.sales_blitz', name='sales_blitz'),
    url(r'^sales-blitz/(?P<plan_slug>\S+)', 'base.views.sales_blitz', name='sales_blitz'),

    url(r'^sample-blitz$', 'base.views.sales_blitz', name='sample_blitz'),
    url(r'^sample-blitz/(?P<plan_slug>\S+)', 'base.views.sales_blitz', name='sample_blitz'),

    url(r'^termsofuse$', 'base.views.terms_of_use', name='terms_of_use'),
    url(r'^privacypolicy$', 'base.views.privacy_policy', name='privacy_policy'),

    url(r'^profile/settings$', 'base.views.client_settings', name='client_settings'),
    url(r'^404$', 'base.views.page404', name="page404"),
    url(r'^500$', 'base.views.page500', name="page500"),

    url(r'^set-timezone$', 'base.views.set_timezone', name='set_timezone'),
    url(r'^set-units$', 'base.views.set_units', name='set_units'),

    url(r'^trainer/go-to-blitz', 'base.views.trainer_switch_blitz', name='trainer_switch_blitz'),

    url(r'^inbox$', 'ff_messaging.views.inbox', name='inbox'),
    url(r'^messages/new$', 'ff_messaging.views.new_message', name='new_message'),
    url(r'^messages/user/(?P<pk>\w+)/new$', 'ff_messaging.views.new_message_to_user', name='new_message_to_user'),
    url(r'^messages/thread/(?P<urlkey>\w+)$', 'ff_messaging.views.user_thread', name='user_thread'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),

    # blitz URLs
#    url(r'^blitz/(?P<url_slug>[a-zA-Z0-9_.-]+)/([\w|-]+)/create_account', 'base.views.create_account_hook', name='create_account_hook'),
    url(r'^blitz/(?P<pk>\d+)/([\w|-]+)/create_account', 'base.views.create_account_hook', name='create_account_hook'),

#    url(r'^blitz/(?P<url_slug>[a-zA-Z0-9_.-]+)/([\w|-]+)/payment_hook', 'base.views.payment_hook', name='payment_hook'),
    url(r'^blitz/(?P<pk>\d+)/([\w|-]+)/payment_hook', 'base.views.payment_hook', name='payment_hook'),

    url(r'^blitz-setup$', 'base.views.blitz_setup', name='blitz_setup'),

    url(r'^blitz_macros/(?P<pk>\d+)$', 'base.views.blitz_macros', name='blitz_macros'),
    url(r'^client_macros/(?P<pk>\d+)$', 'base.views.client_macros', name='client_macros'),

    url(r'^spotter_program_edit/(?P<pk>\d+)$', 'base.views.spotter_program_edit', name='spotter_program_edit'),

    url(r'^(?P<short_name>[a-zA-Z0-9_.-]+)/(?P<url_slug>[a-zA-Z0-9_.-]+)/signup$', 'base.views.blitz_signup', name="blitz_signup"),

    url(r'^(?P<short_name>[a-zA-Z0-9_.-]+)/(?P<url_slug>[a-zA-Z0-9_.-]+)/signup-complete$', 'base.views.blitz_signup_done', name='blitz_signup_done'),

    url(r'^(?P<short_name>[a-zA-Z0-9_.-]+)/signup$', 'base.views.default_blitz_signup', name="default_blitz_signup"),
    url(r'^signup-complete$', 'base.views.blitz_signup_done', name='blitz_signup_done'),

    url(r'^(?P<short_name>[a-zA-Z0-9_.-]+)$', 'base.views.default_blitz_page', name="default_blitz_page"),

workouts/models.py
from django.db import models
import datetime
import itertools

DAYS_OF_WEEK = (
    ('M', 'Monday'),
    ('T', 'Tuesday'),
    ('W', 'Wednesday'),
    ('H', 'Thursday'),
    ('F', 'Friday'),
    ('S', 'Saturday'),
    ('U', 'Sunday'),
)

LIFT_TYPES = (
    ('R', 'Reps'),
    ('I', 'Interval'),
)

class Lift(models.Model):
    """
    Lift at the gym - eg Bench Press
    """

    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100, default="")



    # can this be done with weighed / assisted / body weight (eg. chinup)
    weight_or_body = models.BooleanField(default=False, verbose_name='Bodyweight exercise?')
    allow_weight_or_body = models.BooleanField(default=True, verbose_name='If body weight, can it be weighted (e.g. like a pull-up)?')
    lift_type = models.CharField(max_length=1, default="R", choices=LIFT_TYPES)

    def __unicode__(self):
        return self.name


class Workout(models.Model):
    """
    Sum of what you do when you go to the gym
    Includes a set of WorkoutSets
    """

    display_name = models.CharField(max_length=100)
    description = models.CharField(max_length=400, default="")

    # Sets are not necessarily grouped by lift - a workout could prescribe bench -> squat -> bench
    # But, usually sets are going to be grouped, so indicate that here
    # Some templates presumably will only render if grouped
    sets_grouped = models.BooleanField(default=True)

    # not for display; only for keeping track of workouts internally
    slug = models.SlugField(max_length=100)

    def __unicode__(self):
        return self.display_name

    def get_lifts(self):
        """
        Unique lifts in this workout
        """
        return list(set(ws.lift for ws in self.workoutset_set.all()))

    def get_exercises(self):
        return self.exercise_set.all().order_by('order')


class Exercise(models.Model):
    lift = models.ForeignKey(Lift)
    workout = models.ForeignKey(Workout)
    sets_display = models.CharField(max_length=100, default="")
    description = models.CharField(max_length=400, default="")
    order = models.FloatField(default=0.0)

    def num_sets(self):
        return self.workoutset_set.all().count()

    # description can be multi-part separated by '|', eg. '1.0 | a description for the exercise'
    def prefix(self):   # return prefix in description
        if '|' in self.description:
            return self.description[:self.description.index('|')]
        elif len(self.description)<5:
            return self.description 

    def desc(self):   # return description portion of description
        if '|' in self.description:
            return self.description[self.description.index('|')+1:]
        elif len(self.description)>5:
            return self.description 
       
    def __unicode__(self):
        return "%s of %s in %s" % ( self.sets_display, str(self.lift), str(self.workout) )

# custom exercise record for client
class ExerciseCustom(models.Model):
    client = models.ForeignKey('base.Client')
    exercise = models.ForeignKey(Exercise)

    lift = models.ForeignKey(Lift)
    sets_display = models.CharField(max_length=100, default="")
    date_created = models.DateField(("Date"), default=datetime.date.today)

    def __unicode__(self):
        return "%s of %s (replaces %s) in %s (as of %s)" % ( self.sets_display, str(self.lift), self.exercise.lift.name, str(self.exercise.workout), self.date_created )


class WorkoutSet(models.Model):
    """
    One set in a workout - eg. 10 reps of bench press
    Note that no weight totals here
    """

    lift = models.ForeignKey(Lift) # remove, duplicative
    workout = models.ForeignKey(Workout)
    num_reps = models.IntegerField()
    exercise = models.ForeignKey(Exercise, null=True)

    # order that set should be done; lower comes first
    # if workout.sets_grouped, order is applied *after* grouping
    order = models.FloatField(default=0.0)

    def __unicode__(self):
        return "%d reps of %s in %s" % ( self.num_reps, str(self.lift), str(self.workout) )

# custom workoutset record for client
class WorkoutSetCustom(models.Model):
    client = models.ForeignKey('base.Client')
    workoutset = models.ForeignKey(WorkoutSet)

    lift = models.ForeignKey(Lift)
    num_reps = models.IntegerField()
    date_created = models.DateField(("Date"), default=datetime.date.today)

    def __unicode__(self):
        return "%d reps of %s in %s" % ( self.num_reps, str(self.lift), str(self.workoutset.workout) )


class WorkoutPlan(models.Model):
    """
    A full workout plan (program)
    """

    name = models.CharField(max_length=100, default="")

    trainer = models.ForeignKey('base.Trainer', null=True)

    def __unicode__(self):
        if self.trainer:
            return "%s (pk:%d) trainer:%s" % (self.name, self.pk, self.trainer.name)
        else:
            return "%s (pk:%d)" % (self.name, self.pk)

    def num_weeks(self):
        return self.workoutplanweek_set.count()

    def get_workout_for_day(self, week, day):
        try:
            week = self.workoutplanweek_set.get(week=week)
            day = week.workoutplanday_set.get(day_of_week=day)
            return day
        except ObjectDoesNotExist:
            return None

    def iterate_days(self):
        """
        generator of workoutplandays in order
        """
        for workout_plan_week in self.workoutplanweek_set.all().order_by('week'):
            for workout_plan_day in workout_plan_week.workoutplanday_set.all().order_by('day_index'):
                yield workout_plan_day

    def all_lifts(self):
        try:
            return list(set([d.workout.get_lifts()[0] for d in self.iterate_days()]))
        except:
            return []

    def weeks(self):
        return self.workoutplanweek_set.all().order_by('week')

    def workouts(self):
        days = [week.workoutplanday_set.all() for week in self.workoutplanweek_set.all()]  # get all days
        days_set = set(itertools.chain(*days))   # flatten array
        return set([day.workout for day in days_set])   # return set of workouts

class WorkoutPlanWeek(models.Model):
    """
    One week in a plan
    Contains a set of workout days with meta info, sometimes content like an article of the week
    *** WEEKS ARE ALWAYS 1-INDEXED ***
    """

    workout_plan = models.ForeignKey(WorkoutPlan)

    # *** WEEKS ARE ALWAYS 1-INDEXED ***
    week = models.IntegerField()

    def __unicode__(self):
        return "Week %d of %s" % ( self.week, str(self.workout_plan) )

    def days(self):
        return self.workoutplanday_set.all().order_by('day_index')

class WorkoutPlanDay(models.Model):
    """
    Workout embedded in a day of a plan
    """

    workout_plan_week = models.ForeignKey(WorkoutPlanWeek)
    day_of_week = models.CharField(max_length=1, choices=DAYS_OF_WEEK)
    day_index = models.IntegerField(default=-1)
    workout = models.ForeignKey(Workout)

    def __unicode__(self):
        return "%s of %s" % (
            self.day_of_week,
            str(self.workout_plan_week)
        )

    def get_workout_plan(self):
        return self.workout_plan_week.workout_plan

    def get_week(self):
        return self.workout_plan_week.week

    def get_day_name(self):
        return DAYS_OF_WEEK[self.day_index][1]

    def save(self, *args, **kwargs):
        self.day_index = next(i for i, d in enumerate(DAYS_OF_WEEK) if d[0] == self.day_of_week)
        super(WorkoutPlanDay, self).save(*args, **kwargs)

helper/templates/assign_workoutplan.html
{% extends "helper_base.html" %}

{% block main %}
<header> Assign program</header>
<div class="span8">

<div class="content">
    <form enctype="multipart/form-data" action="assign_workoutplan?plan={{ workoutplan.pk }}" method="post" name="program_create" class="formpage-block-form">{% csrf_token %}

        <select name="trainer_id" id="trainer_id">
        {% for trainer in trainers %}
            <option value="{{trainer.id}}"{% if trainer = workoutplan.trainer %}selected{% endif %}>
            {{trainer.name}} 
            </option>
        {% endfor %}
        </select>
        WorkoutPlan name: {{ workoutplan.name }} <small>--></small>
        Assign to blitz: <select name="blitz_id" id="blitz_id">
        {% for blitz in blitzes %}
            <option value="{{blitz.id}}">
            {{blitz.title}}
            </option>
        {% endfor %}
        </select>

     <div class="submit-container">
        <button class='obtn full-width' type='submit'>Assign</button>{% csrf_token %}
     </div>
</form>
</div>

<ul>
{% for e in errors %}
    <li>{{ e }}</li>
{% endfor %}
</ul>
</div>


{% endblock %}

helper/templates/custom_exercise_page.html
{% extends "helper_base.html" %}

{% block main %}
<header> Customize Exercise </header>
{{ exercise }} {% if workoutset.client %} for {{ workoutset.client }} {% endif %}
<div class="span8">

        <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
        <input type="text" name="sets_display" value="{{ exercise.sets_display }}" />

        <select name="lift" id="lift">
        {% for l in lifts|dictsort:"name" %}
            <option value="{{l.id}}"
        {% if l.id == exercise.lift_id %}selected{% endif %}>
            {{l.name}}</option>
        {% endfor %}
        </select>

        <select name="client" id="client">
        {% for member in members %}
            <option value="{{member.client.pk}}"
        {% if member.client.pk == workoutset.client.pk %}selected{% endif %}>
            {{member.client.name}}</option>
        {% endfor %}
        </select>
        <br>
        <div class="submit-container">
            <button class='obtn full-width' type='submit'>Update</button>
        </div>
        </form>

</div>

{{ form.errors }} 


{% endblock %}

helper/templates/custom_set_page.html
{% extends "helper_base.html" %}

{% block main %}
<header> Customize WorkoutSet </header>
{{ workoutset }} {% if workoutset.client %} for {{ workoutset.client }} {% endif %}
<div class="span8">

        <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
        <input type="text" name="num_reps" value="{{ workoutset.num_reps }}" />

        <select name="lift" id="lift">
        {% for l in lifts|dictsort:"name" %}
            <option value="{{l.id}}"
        {% if l.id == workoutset.lift_id %}selected{% endif %}>

            {{l.name}}</option>
        {% endfor %}
        </select>

        <select name="client" id="client">
        {% for member in members %}
            <option value="{{member.client.pk}}"
        {% if member.client.pk == workoutset.client.pk %}selected{% endif %}>
            {{member.client.name}}</option>
        {% endfor %}
        </select>
        <br>
        <div class="submit-container">
            <button class='obtn full-width' type='submit'>Update</button>
        </div>
        </form>

</div>

{{ form.errors }} 


{% endblock %}

helper/templates/docs.html
{% extends "helper_base.html" %}

{% block main %}
<style>
      tr:nth-of-type(odd) {
      background-color:#D8F1D7;
    }
</style>
<header>There are {{ numdocs }} documents to process <br></header>
<table>
{% for doc in docs %}
<tr>
<td><a href="{% url "helper_download" %}?file={{ doc.doc }}&dir=/documents/">
{{ doc.name }} on {{ doc.day }}/{{ doc.month }}/{{ doc.year}} at {{ doc.hour }}:{{ doc.minute }}:{{doc.second}}</a></td>
<td><small>(<a href="{% url "helper_delete" %}?file={{ doc.doc }}">Delete</a>)</small></td>
</tr>
{% endfor %}
</table>
<br>


{% endblock %}

helper/templates/exercises_page.html
{% extends "helper_base.html" %}

{% block main %}

<header>Here are the workoutsets and exercises for workout: {{ workout.display_name }}</header>
<small>Note: that "sets" and "reps" pertain to workout logging reps while "exercises" pertain to all other workout displays.<br>Note: custom entries listed chronologically (last entry is the one used)</small>
<style>
      tr:nth-of-type(odd) {
      background-color:#D8F1D7;
    }
</style>

{% regroup workoutset by exercise.lift.name as lift_list %}
{% for lift in lift_list %}
<ul><li> {{ lift.grouper }}</li>
    <table>
    {% regroup lift.list by exercise.sets_display as set_list %}
    {% for workoutset in set_list %}
    <tr><td>{{ workoutset.grouper }}</td>
        {% if workoutset.list.0.exercise.exercisecustom_set.all %}
            {% for c in workoutset.list.0.exercise.exercisecustom_set.all %}
            <tr><td>custom: {{ c.sets_display }}</td>
            <td><small>custom:</small>{{ c.lift }}</td>
            <td><a href="custom_exercise?custom_id={{ c.pk }}"><small>(for {{ c.client }} on {{ c.date_created }})</small></a></td></tr>
            {% endfor %}
        {% endif %}
            <td><a href="custom_exercise?id={{ workoutset.list.0.exercise.id }}">create exercise</a></td>
    </tr>
        {% for w in workoutset.list %}
        <tr><td><small>order:</small>{{ w.exercise.order }}</td>

        <td><small>reps:</small>{{ w.num_reps }}</td>
        {% if w.workoutsetcustom_set.all %}
            {% for c in w.workoutsetcustom_set.all %}
            <tr><td>
            <td>reps:{{ c.num_reps }}</td>
            <td><a href="custom_workoutset?custom_id={{ c.pk }}"><small>(for {{ c.client }} on {{ c.date_created }})</small></a></td>
            {% endfor %}
        {% endif %}
        <td><a href="custom_workoutset?id={{ w.pk }}">create set</a></td>
        </tr>
        {% endfor %}

    {% endfor %}
    </table></ul>
{% endfor %}


{% if errors %}
    <ul>
    {% for e in errors %}
        <li>{{ e }}</li>
    {% endfor %}
    </ul>
{% endif %}

<br>


{% endblock %}

helper/templates/helper_base.html
<<<<<<< HEAD
{% extends "base.html" %}

{% block body_extras %}class="login-page"{% endblock %}

{% block outer_content %}

<style type="text/css">
	.container {
		text-align: center !important;
		color: white !important;
		list-style: none !important;
		margin-top: 5%;
	}
	.container a {
		color: cornflower-blue !important;

	}

	.blitz-login, img {
		/*  */padding: 0 important!;
		margin-bottom: 30px;
	}

	.header ul {
		list-style-type: none !important;
		margin-top: 20px;
		margin-bottom: 20px;
	}

	ul {
		margin: 30px 0px 0px 0px;
	}

	li {
		
		list-style-type: none !important;
	}

	table {
		width: 100%;
	}



	tr:nth-of-type(odd) {
	background-color: rgba(255,255,255,0.15) !important;
	}

	tr {
		height: 50px;
	}

</style>

<div class="container">
    <div class="row">
        <div class="span10 offset1" style="margin-bottom: 50px;">
            <div class="xblitz-login" style="margin-top: 20% important!;">
                <a href="{% url "helper_index" %}"><img src="{{ STATIC_URL }}images/logo-w.png" /></a>
            </div>
        <div class="" style="margin-bottom: 30px;">
	        <ul class="helpernav">
				<li><a href="{% url "helper_index" %}">Home</a></li>
				<li><a href="{% url "helper_usage" %}">Daily Digest</a></li>
				<li><a href="{% url "helper_uploads" %}">Trainers Uploads</a></li>
				<li><a href="{% url "helper_program_upload" %}">Upload Programs</a></li>
				<li><a href="{% url "helper_pending_trainers" %}">Pending Trainers/Plans</a></li>
				<li><a href="{% url "helper_status_trainers" %}">Trainers, Blitzes, and WorkoutPlans</a></li>
				<li><a href="{% url "helper_blitz_sales_pages" %}">Sales Pages</a></li>
				<li><a href="{% url "helper_workouts" %}">Exercises and Workout-sets</a></li>
			</ul>
		</div>
                {% block main %}
				{% endblock %}
        </div>
    </div>
    
</div>
{% endblock outer_content %}

=======
<a class="brand" href="/" id="logo"><img src="{{ STATIC_URL }}images/logo-bp2.png"/></a><br>
<style>body { font-family: Ubuntu, sans-serif; }</style>
>>>>>>> master

helper/templates/pending_sales_pages.html
{% extends "helper_base.html" %}

{% block main %}

<header>Here are the blitz sales pages</header>
<style>
      tr:nth-of-type(odd) {
      background-color:#D8F1D7;
    }
</style>
<table>

{% for content in pending %}
<tr>
    {% for element in content %}
      {% if forloop.first %}
        <td>id:<a href="program_sales_page?plan={{ element }}"><b>{{ element }}</b></a></td>
      {% else %}
        <td>{{ element }}</td>
      {% endif %}
    {% endfor %}
</tr>
{% endfor %}
</table>
{% if errors %}
    <ul>
    {% for e in errors %}
        <li>{{ e }}</li>
    {% endfor %}
    </ul>
{% endif %}

<br>


{% endblock %}

helper/templates/program_create_done_page.html
{% extends "helper_base.html" %}

{% block main %}
<header> Program creation results</header>
<div class="span8">

Program <b>{{ plan_name }}</b> created successfully for traider id #{{ trainer_id }}
</div>
<br>

{% endblock %}